<?php
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_extra_field_info().
 */
function wendys_product_slider_entity_extra_field_info() {
  $extra = array();

  $extra['brick']['product_slider']['display']['product_slider'] = array(
    'label' => t('Product Slider'),
    'description' => t('Slider of products returned from WIMs.'),
    'weight' => 100,
    'visible' => TRUE,
  );

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function wendys_product_slider_brick_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('product_slider')) {
    $build['product_slider'] = [
      '#theme' => 'product_slider',
    ];
  }
}

/**
 * Implements hook_theme().
 */
function wendys_product_slider_theme($existing, $type, $theme, $path) {
  return array(
    'product_slider' => array(
      'template' => 'product-slider',
      'variables' => array(
        'items' => [],
      ),
    ),
  );
}

/**
 *
 */
function wendys_product_slider_preprocess(&$variables, $hook) {
  if ($hook === 'product_slider') {
    $items = [];

    $items[] = [
      'url' => 'https://menu.wendys.com/en_US/category/our-picks/',
      'label' => 'Featured Items',
      'img' => 'https://www.wendys.com/assets/0a9452a26920278fc3200d93a519b004.jpg',
    ];
    $items[] = [
      'url' => 'https://menu.wendys.com/en_US/category/our-picks/',
      'label' => 'Hamburgers',
      'img' => 'https://www.wendys.com/assets/5a96216736f8e47506e430a2c13b731a.jpg',
    ];
    $items[] = [
      'url' => 'https://menu.wendys.com/en_US/category/our-picks/',
      'label' => 'Chicken, Wraps & More',
      'img' => 'https://www.wendys.com/assets/0a9452a26920278fc3200d93a519b004.jpg',
    ];
    $items[] = [
      'url' => 'https://menu.wendys.com/en_US/category/our-picks/',
      'label' => 'Fresh-Made Salads',
      'img' => 'https://www.wendys.com/assets/5a96216736f8e47506e430a2c13b731a.jpg',
    ];
    $items[] = [
      'url' => 'https://menu.wendys.com/en_US/category/our-picks/',
      'label' => 'Fries & Sides',
      'img' => 'https://www.wendys.com/assets/0a9452a26920278fc3200d93a519b004.jpg',
    ];
    $items[] = [
      'url' => 'https://menu.wendys.com/en_US/category/our-picks/',
      'label' => 'Beverages',
      'img' => 'https://www.wendys.com/assets/5a96216736f8e47506e430a2c13b731a.jpg',
    ];
    $items[] = [
      'url' => 'https://menu.wendys.com/en_US/category/our-picks/',
      'label' => 'Frosty',
      'img' => 'https://www.wendys.com/assets/0a9452a26920278fc3200d93a519b004.jpg',
    ];
    $items[] = [
      'url' => 'https://menu.wendys.com/en_US/category/our-picks/',
      'label' => 'Bakery',
      'img' => 'https://www.wendys.com/assets/5a96216736f8e47506e430a2c13b731a.jpg',
    ];
    $items[] = [
      'url' => 'https://menu.wendys.com/en_US/category/our-picks/',
      'label' => 'Wendy\'s Kinds\' Meal',
      'img' => 'https://www.wendys.com/assets/0a9452a26920278fc3200d93a519b004.jpg',
    ];
    $items[] = [
      'url' => 'https://menu.wendys.com/en_US/category/our-picks/',
      'label' => 'Right Price Right Size',
      'img' => 'https://www.wendys.com/assets/5a96216736f8e47506e430a2c13b731a.jpg',
    ];
    $items[] = [
      'url' => 'https://menu.wendys.com/en_US/category/our-picks/',
      'label' => 'Meal Deals',
      'img' => 'https://www.wendys.com/assets/0a9452a26920278fc3200d93a519b004.jpg',
    ];
    $items[] = [
      'url' => 'https://menu.wendys.com/en_US/category/our-picks/',
      'label' => 'Breakfast',
      'img' => 'https://www.wendys.com/assets/5a96216736f8e47506e430a2c13b731a.jpg',
    ];

    $variables['items'] = $items;
  }
}