#!/usr/bin/env bash

## Build Project and artifacts
##
## Usage: fin builder

#-------------------------- Helper functions --------------------------------

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/../functions.sh"

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Initialize local settings files
init_settings () {
  # Copy from settings templates
  copy_settings_file "${SITES_PATH}/example.settings.docksal.php" "${SITEDIR_PATH}/settings.docksal.php"
}

# Fix file/folder permissions
fix_permissions () {
  chmod 755 "${SITEDIR_PATH}"
}

# Fix file/folder permissions
fix_docker_permissions () {
  fin fix_permissions
}

# Fix file/folder permissions
fix_submodules () {
  find vendor -type d -name ".git" -prune -exec rm -rf {} \;
  find docroot/libraries -type d -name ".git" -prune -exec rm -rf {} \;
  find docroot/modules/contrib -type d -name ".git" -prune -exec rm -rf {} \;
  find docroot/themes/contrib -type d -name ".git" -prune -exec rm -rf {} \;
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Sanity Check --------------------------------

if [[ "$PROJECT_ROOT" == "" ]]; then
  echo-red "\$PROJECT_ROOT is not set"
  exit 1
fi

#-------------------------- END: Sanity Check --------------------------------

#-------------------------- Execution --------------------------------

header "Building Site"
section=Build
step=1

# Project initialization steps
step_header "Initializing local project"
fix_permissions
init_settings

if [[ $DOCKER_RUNNING == "false" ]]; then
  step_header "Starting services"
  fin up
fi

step_header "Fix docker permissions"
fix_docker_permissions

step_header "Installing composer"
fin composer install --prefer-dist --no-dev --no-progress -o

step_header "Building front end artifacts"
fin util
fin febuild npm yarn bower gulp-build

step_header "Cleaning git submodules..."
fix_submodules

#-------------------------- END: Execution --------------------------------