#!/usr/bin/env bash

## Install required utilities for other commands
##
## Usage: fin util


#-------------------------- Helper functions --------------------------------

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/../functions.sh"

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Sanity Check --------------------------------

if [[ "$PROJECT_ROOT" == "" ]]; then
  echo-red "\$PROJECT_ROOT is not set"
  exit 1
fi

#-------------------------- END: Sanity Check --------------------------------

#-------------------------- Execution --------------------------------

subheader "Installing utilities"

cd $PROJECT_ROOT

fin exec yarn global add eslint bower yaml-cli eslint-config-airbnb-base@12.1.0 eslint-plugin-import@2.2.0 eslint-config-airbnb@14.1.0 eslint-plugin-jsx-a11y@4.0.0 eslint-plugin-react@6.10.3  --no-progress --quiet

#-------------------------- END: Execution --------------------------------
#fin exec sudo ln -s /home/docker/.yarn/bin/yaml /usr/bin/yaml > /dev/null 
#fin exec sudo ln -s /home/docker/.yarn/bin/eslint /usr/bin/eslint > /dev/null 
#fin exec sudo ln -s /home/docker/.yarn/bin/bower /usr/bin/bower > /dev/null 

